package com.abc.soa;

/**
 * @author JiangZuoWei
 * @createTime 2015年11月11日 下午2:14:22
 * @description
 */
public enum ConstantsUri {

    /* 帮帮接口 */
    SYSTEMRECORD_LIST("系统使用记录","/bangbang/system/record"),
    SYSTEMRECORD_INFO("系统使用记录单","/bangbang/system/record/{id}"),
    PUB_HOTQUESTION("热点问题","/bangbang/knowledgeBase/hotUnClassifyList"),
    PUB_HOTDISCUSSION("帮帮热议","/bangbang/hotspot/comments"),
    PUB_NEWESTCURRICULUM("最新课程","/bangbang/curriculum/selectListNew"),
    PUB_HOTTAGS("获取所有内容标签列表","/cms/content/selectContentType"),
    KNOW_CATE_LIST("知识库分类列表","/bangbang/knowledgeCategory/listAll"),
    KNOW_KNOWLEDGEBASE_LIST("根据知识库分类查询知识库内容","/bangbang/knowledgeBase/list"),
    KNOW_CATE_ADD("新增知识库分类","/bangbang/knowledgeCategory/add"),
    KNOW_CATE_MODIFY("修改知识库分类","/bangbang/knowledgeCategory/modify"),
    KNOW_CATE_MODIFYNAME("修改知识分类名称","/bangbang/knowledgeCategory/modifyName/{id}"),
    KNOW_CATE_DELETE("删除知识分类","/bangbang/knowledgeCategory/delete/{id}"),
    KNOW_CON_LABEL("获取问答知识关联标签","/bangbang/KnowledgeTag/list/{knowledgeId}"),
    KNOW_TAG("查询知识标签","/bangbang/KnowledgeTag/{id}"),
    KNOW_TAG_LIST("查询知识标签列表","/bangbang/KnowledgeTag/list"),
    KNOW_TAG_ADD("新增知识库标签","/bangbang/KnowledgeTag/add"),
    KNOW_TAG_BATCH_ADD("批量新增知识库标签","/bangbang/KnowledgeTag/batch/add"),
    KNOW_TAG_BATCH_ADD_OTHER_CHANNEL("批量新增知识库标签","/bangbang/KnowledgeTag/addByOtherChannel"),
    KNOW_TAG_MODIFY("修改知识库标签","/bangbang/KnowledgeTag/modify"),
    KNOW_TAG_DELETE("删除知识库标签","/bangbang/KnowledgeTag/delete/{id}"),
    KNOW_TAG_BATCH_DELETE("批量删除知识库标签","/bangbang/KnowledgeTag/batch/delete"),
    KNOW_TAG_ENABLE("启用禁用知识库标签","/bangbang/KnowledgeTag/modifyStatus/{id}/{status}"),
    KNOW_ADD("添加问答知识","/bangbang/knowledgeBase/add"),
    KNOW_MODIFY("修改问答知识","/bangbang/knowledgeBase/modify"),
    KNOW_VIEW("获取问答知识对象","/bangbang/knowledgeBase/view/{id}"),
    KNOW_CON("获取问答知识关联问题","/bangbang/knowledgeBase/relatedList/{id}"),
    KNOW_DELLETE("删除问答知识","/bangbang/knowledgeBase/delete"),
    KNOW_UPDATE_STATUS("启用/禁用问答知识","/bangbang/knowledgeBase/modifyStatus"),
    KNOW_VOTE_LIST("知识库投票列表","/bangbang/knowledgeBase/vote/list"),
    KNOW_VOTE_DELETE("删除知识库投票","/bangbang/knowledgeBase/vote/delete/{id}"),
    KNOW_VOTE_BATCH_DELETE("批量删除知识库投票","/bangbang/knowledgeBase/vote/delete"),
    FEEDBACK_LIST("意见反馈列表","/bangbang/feedback/list"),
    FEEDBACK_DELETE("意见反馈删除","/bangbang/feedback/delete/{id}"),
    FEEDBACK_DELETE_LIST("意见反馈批量删除","/bangbang/feedback/delete"),
    COURSE_VIEW("课程查询","/bangbang/curriculum/{curriculumId}"),
    COURSE_LIST("课程列表查询","/bangbang/curriculum"),
    COURSE_ADD("课程新增","/bangbang/curriculum"),
    COURSE_EDIT("课程修改","/bangbang/curriculum/{curriculumId}"),
    COURSE_DELETE("课程删除","/bangbang/curriculum/{curriculumId}"),
    COURSE_BROWSERWATCH_DAY_LIST("课程浏览观看数日期数据","/bangbang/curriculumBrowserWatch/selectList"),
    COURSE_BROWSERWATCH_MONTH_LIST("课程浏览观看数月份数据","/bangbang/curriculumBrowserWatch/selectMonthList"),


    SELECT_BY_SUBJECT("知识库标题模糊查询","/bangbang/knowledgeBase/selectBySubject"),
    MODIFY_CATEGORY_CODE("批量修改知识库类别","/bangbang/knowledgeBase/modifyCategoryCode"),
    MODIFY_TAG("批量修改知识库标签","/bangbang/knowledgeBase/modifyTag"),


    COURSE_UPDATE_STATUS("课程状态修改","/bangbang/curriculum/updateStatus/{curriculumId}"),
    COURSE_CATEGORY("课程分类列表查询","/bangbang/classify"),
    COURSE_CATEGORY_ADD("课程分类新增","/bangbang/classify"),
    COURSE_CATEGORY_MODIFY("课程分类修改","/bangbang/classify/updateClassify/{classifyId}"),
    COURSE_CATEGORY_DELETE("课程分类删除","/bangbang/classify/{classifyId}"),
    COURSE_LECTURER_LIST("课程讲师列表查询","/bangbang/lecturer"),
    COURSE_LECTURER("课程讲师查询修改删除","/bangbang/lecturer/{id}"),
    COURSE_LECTURER_ADD("课程讲师新增","/bangbang/lecturer"),
    COURSE_CHAPTER("课程章节","/bangbang/chapter"),
    COURSE_CHAPTER_ID("课程章节查询/删除/更新","/bangbang/chapter/{chapterId}"),
    COURSE_COURSEWARE("课程课件新增/列表查询","/bangbang/courseware"),
    COURSE_COURSEWARE_LIST("课件素材库列表查询","/bangbang/courseware/list"),
    COURSE_COURSEWARE_ID("课程课件查询/删除/更新","/bangbang/courseware/{coursewareId}"),
    COURSE_STUDY("课程学习情况","/bangbang/currStudy"),
    COURSE_SIGN("课程签到情况","/bangbang/currApply"),
    COURSE_ORDER("课程订购情况","/uc/order/curriculum"),
    COURSE_SITUATION("课程授课信息","/bangbang/curriculum/selectSituation/{curriculumId}"),
    CURRICULUM_KJ_ID("查询课件具体信息","/bangbang/courseware/{coursewareId}"),
    CURRICULUM_DETAILS("课堂详情信息","/bangbang/curriculum/selectCurriculum2/{curriculumId}"),
    COURSE_CATEGORY_TAG("课程分类标签查询","/bangbang/classify/selectClassifyTagList"),
    COURSE_CATEGORY_TAG_MODIFY("课程分类标签修改","/bangbang/classify/{classifyId}"),
    COURSE_ADDTAG_AND_REFCLASSIFY("添加课程分类标签","/bangbang/classify/addTagAndRefClassify"),

    CUSTOMER_SERVICE_ORDER("客户服务单信息查询","/bangbang/accepted/admin/list"),

    BANGBANG_TODOLIST("帮帮运营看板数据","/bangbang/todoList"),
    BANGBANG_TOPICRECOMMEND_LIST("话题推荐管理列表查询","/bangbang/questionbb/selectListTopicRecommend"),
    BANGBANG_TOPICRECOMMEND_RECOMMEND("话题推荐管理是否推荐","/bangbang/questionbb/recommend/{id}/{isRecommend}"),
    BANGBANG_QUESTION_VIEW("帮帮问题详情","/bangbang/questionbb/selectQuestion/{id}"),
    BANGBANG_QUESTION_ANSWER_VIEW("帮帮问题回答详情","/bangbang/queAnswer/selectAnswer/{id}"),
    BANGBANG_QUESTION_COMMENT_VIEW("帮帮问题评论详情","/bangbang/queComment/{id}"),
    BANGBANG_CHEAT_VIEW("帮帮秘籍详情","/bangbang/cheats/{id}"),
    BANGBANG_CHEAT_COMMENT_VIEW("帮帮秘籍评论详情","/bangbang/cheatsComment/{id}"),
    BANGBANG_CHEATS_RECOMMEND("话题推荐管理是否推荐","/bangbang/cheats/recommend/{id}/{isRecommend}"),
    BANGBANG_QUESTION_CLASSIFY_LIST("帮帮分类查询","/bangbang/queclassify"),
    BANGBANG_QUESTION_CLASSIFY_ADD("帮帮分类新增","/bangbang/queclassify"),
    BANGBANG_QUESTION_CLASSIFY_MODIFY("帮帮分类修改","/bangbang/queclassify/{classifyCode}"),
    BANGBANG_QUESTION_CLASSIFY_DELETE("帮帮分类删除","/bangbang/queclassify/{classifyCode}"),
    BANGBANG_QUESTION_CLASSIFYTAG("帮帮分类标签查询","/bangbang/queclassify/selectClassifyTagList"),
    BANGBANG_QUESTION_CLASSIFYTAG_MODIFY("帮帮分类标签修改","/bangbang/queclassify/updateClassifyTag"),

    BANGBANG_QUESTION_HEADMAN_LIST("帮帮掌门人列表","/bangbang/questionHeadman/list"),
    BANGBANG_QUESTION_HEADMAN_VIEW("帮帮掌门人详情","/bangbang/questionHeadman/view/{id}"),
    BANGBANG_QUESTION_HEADMAN_MODIFYSTATUS("帮帮掌门人申请审批","/bangbang/questionHeadman/modifyStatus"),
    BANGBANG_QUESTION_SYSBLOCK_LIST("帮帮系统过滤内容列表","/bangbang/questionSysBlock/list"),
    BANGBANG_QUESTION_SYSBLOCK_STATUS("帮帮系统过滤内容状态修改","/bangbang/questionSysBlock/status/{id}/{status}"),
    BANGBANG_QUESTION_TIPOFF_LIST("帮帮举报内容列表","/bangbang/questionTipOff/list"),
    BANGBANG_QUESTION_TIPOFF_VIEW("帮帮举报内容单个查询","/bangbang/questionTipOff/view/{id}"),
    BANGBANG_QUESTION_TIPOFF_STATUS("帮帮举报内容状态修改","/bangbang/questionTipOff/modifyStatus"),
    BANGBANG_QUESTION_DISABLEUSER_LIST("帮帮禁言用户管理列表","/bangbang/questionDisableUser/list"),
    BANGBANG_QUESTION_DISABLEUSER_DISABLE("帮帮用户禁言","/bangbang/questionDisableUser/disable"),
    BANGBANG_QUESTION_DISABLEUSER_ENABLE("帮帮用户撤销禁言","/bangbang/questionDisableUser/enable/{userId}"),
    BANGBANG_QUESTION_DISABLEIP_LIST("帮帮IP管理列表","/bangbang/questionDisableIp/list"),
    BANGBANG_QUESTION_DISABLEIP_DISABLE("帮帮IP禁言","/bangbang/questionDisableIp/disable"),
    BANGBANG_QUESTION_DISABLEIP_ENABLE("帮帮IP撤销禁言","/bangbang/questionDisableIp/enable/{ip}"),
    BANGBANG_QUESTION_EXPERT_LIST("帮帮专家列表","/bangbang/questionExpert/list"),
    BANGBANG_QUESTION_EXPERT_VIEW("帮帮专家详情","/bangbang/questionExpert/view/{id}"),
    BANGBANG_QUESTION_EXPERT_ADD("帮帮专家新增","/bangbang/questionExpert/add"),
    BANGBANG_QUESTION_EXPERT_MODIFY("帮帮专家修改","/bangbang/questionExpert/modify"),
    BANGBANG_QUESTION_EXPERT_DELETE("帮帮专家删除","/bangbang/questionExpert/delete/{id}"),
    BANGBANG_QUESTION_MEDAL_LIST("帮帮勋章列表","/bangbang/questionMedal/list"),
    BANGBANG_QUESTION_MEDAL_VIEW("帮帮勋章详情","/bangbang/questionMedal/view/{id}"),
    BANGBANG_QUESTION_MEDAL_ADD("帮帮勋章新增","/bangbang/questionMedal/add"),
    BANGBANG_QUESTION_MEDAL_MODIFY("帮帮勋章修改","/bangbang/questionMedal/modify"),
    BANGBANG_QUESTION_MEDAL_DELETE("帮帮勋章删除","/bangbang/questionMedal/delete/{id}"),
    BANGBANG_SENSITIVEWORDS_LIST("帮帮敏感词列表","/bangbang/sensitiveWords/list"),
    BANGBANG_SENSITIVEWORDS_VIEW("帮帮敏感词详情","/bangbang/sensitiveWords/view/{id}"),
    BANGBANG_SENSITIVEWORDS_ADD("帮帮敏感词新增","/bangbang/sensitiveWords/add"),
    BANGBANG_SENSITIVEWORDS_MODIFY("帮帮敏感词修改","/bangbang/sensitiveWords/modify"),
    BANGBANG_SENSITIVEWORDS_DELETE("帮帮敏感词删除","/bangbang/sensitiveWords/delete/{id}"),

    BANGBANG_FACTIONLEVEL_LIST("帮帮帮派列表","/bangbang/questionFactionLevel/list"),
    BANGBANG_FACTIONLEVEL_VIEW("帮帮帮派详情","/bangbang/questionFactionLevel/view/{id}"),
    BANGBANG_FACTIONLEVEL_ADD("帮帮帮派新增","/bangbang/questionFactionLevel/add"),
    BANGBANG_FACTIONLEVEL_MODIFY("帮帮帮派修改","/bangbang/questionFactionLevel/modify"),
    BANGBANG_FACTIONLEVEL_DELETE("帮帮帮派删除","/bangbang/questionFactionLevel/delete/{id}"),

    BANGBANG_FACTIONMEMBERLEVEL_LIST("帮帮帮手列表","/bangbang/questionFactionMemberLevel/list"),
    BANGBANG_FACTIONMEMBERLEVEL_VIEW("帮帮帮手详情","/bangbang/questionFactionMemberLevel/view/{id}"),
    BANGBANG_FACTIONMEMBERLEVEL_ADD("帮帮帮手新增","/bangbang/questionFactionMemberLevel/add"),
    BANGBANG_FACTIONMEMBERLEVEL_MODIFY("帮帮帮手修改","/bangbang/questionFactionMemberLevel/modify"),
    BANGBANG_FACTIONMEMBERLEVEL_DELETE("帮帮帮手删除","/bangbang/questionFactionMemberLevel/delete/{id}"),

    BANGBANG_FACTIONREWARDSETTING_LIST("帮帮帮派奖励列表","/bangbang/questionFactionRewardSetting/list"),
    BANGBANG_FACTIONREWARDSETTING_ADD("帮帮帮派奖励分配","/bangbang/questionFactionRewardSetting/add"),
    BANGBANG_FACTIONMEMBERREWARD_LIST("帮帮帮派成员奖励分配列表","/bangbang/queFacAllocation/manageList"),
    BANGBANG_FACTIONMEMBERREWARD_AUDIT("帮帮帮派成员奖励分配","/bangbang/queFacAllocation/audit"),

    BANGBANG_QUESTIONCLASSIFY_STATISTICS("帮帮话题分类统计分析","/bangbang/queclassify/selectClassifyStatistics"),



    /* cms接口 */
    PUB_NOTICES("通知公告列表","/cms/notices"),
    CMS_SITE("站点接口", "/cms/site"),
    CMS_SITE_RESTFUL("站点restful接口", "/cms/site/{siteId}"),
    CMS_SITE_PUBLISH("发布全站记录列表", "/cms/siteIssue"),
    CMS_SITE_PUBLISH_CONTENT("获取内容信息发布全站","/cms/content/contentList"),
    CMS_SITE_PUBLISH_CONTENT_GENERATED("批量更新内容已生成静态页字段","/cms/content/updatRegenerateList"),
    CMS_SITE_PUBLISH_COLUMN("获取栏目信息发布全站","/cms/channel/channelList"),
    CMS_SITE_PUBLISH_COLUMN_CONTENT("获取栏目下内容信息发布全站","/cms/content/selectListByChannelId"),
    CMS_TAG_COLUMN_CONTENT("根据内容标签名称、栏目名称查询内容列表信息","/cms/content/selectListByTagName"),
    CMS_CONTENT_PAGES("据多个内容ID获取内容信息","/cms/content/contentListByContentids"),
    CMS_CONTENT_PRE_NEXT("据内容ID获取前后记录信息","/cms/content/selectContentudList"),
    CMS_CONTENT_HOT("查找热门文章","/cms/content/selectListByviews"),
    CMS_SELECT_CONTENT_BY_CHANNELID("根据栏目ID获取内容信息","/cms/content/selectListByChannelId"),
    CMS_SITE_PUBLISH_DELLIST("批量删除发布全站记录","/cms/siteIssue/deleteList"),

    CMS_TEMPLATE_LIST("查看模板信息列表","/cms/template"),
    CMS_TEMPLATE_VIEW("查看单个模板信息","/cms/template/{templateId}"),
    CMS_TEMPLATE_ADD("新增单个模板信息","/cms/template"),
    CMS_TEMPLATE_MOD("修改模板信息","/cms/template/{templateId}"),
    CMS_TEMPLATE_DEL("删除模板信息","/cms/template/{templateId}"),

    CMS_COLUMN("栏目接口", "/cms/channel"),
    CMS_COLUMN_RESTFUL("栏目restful接口", "/cms/channel/{channelId}"),
    CMS_COLUMN_INIT("栏目初始化接口", "/cms/channel/init"),
    CMS_COLUMN_ACTIVE("栏目启用禁用", "/cms/channel/updateByparentId"),
    CMS_SELECT_LIST_BY_CONTENTTYPE("根据栏目ID,内容标签获取内容信息", "/cms/content/selectListByContentType"),
    CMS_SELECT_CONTENTTYPE("根据栏目ID,获取所有内容标签", "/cms/content/selectContentType"),

    CMS_MODEL("查看模型列表", "/cms/model"),
    CMS_MODEL_ID("模型单个接口", "/cms/model/{modelId}"),
    CMS_MODEL_DISABLE("模型启用禁言", "/cms/model/updateIsDisabled"),
    CMS_MODEL_ITEM("模型项列表", "/cms/modelItem"),
    CMS_MODEL_ITEM_ID("模型项列表", "/cms/modelItem/{modelItemId}"),

    CMS_CONTENT("内容接口", "/cms/content"),
    CMS_CONTENT_RESTFUL("内容restful接口", "/cms/content/{contentId}"),
    CMS_CONTENT_INIT("内容初始化接口", "/cms/content/init"),
    CMS_CONTENT_ISSUE("内容发布接口", "/cms/content/updateStatus2/{contentId}"),
    CMS_CONTENT_DELETE_BATCH("内容批量删除接口", "/cms/content/deletelist"),
    CMS_CONTENT_UPDATE_BATCH("内容批量更新接口", "/cms/content/updateList"),
    CMS_CONTENT_SEND_BACK("内容批量退回接口", "/cms/content/thlist"),
    CMS_CONTENT_PUSH_TOPIC("内容批量推送接口", "/cms/content/updatetopicList"),
    CMS_VOTE_LOG("投票记录接口接口","/cms/vote/log/{voteId}"),

    CMS_VOTE("投票接口","/cms/vote"),
    CMS_VOTE_RESTFUL("投票restful接口接口","/cms/vote/{voteId}"),
    CMS_VOTE_STATISTICS("投票统计信息接口","/cms/vote/selecttj"),
    CMS_VOTE_UPDATE_SUBITEM("修改投票项接口","/cms/vote/updateSubItemStatus"),

    CMS_TOPIC("专题接口","/cms/topic"),
    CMS_TOPIC_RESTFULE("专题restful接口","/cms/topic/{topicId}"),
    CMS_TOPIC_DELETE_BATCH("专题批量删除接口","/cms/topic/deleteList"),
    CMS_TOPIC_UPDATE_BATCH("专题批量修改接口","/cms/topic/updateList"),

    CMS_MODEL_DEL_LIST("批量删除模型列表", "/cms/model/deleteList"),
    CMS_MODEL_UPDATE_LIST("批量更新模型列表", "/cms/model/updateList"),
    CMS_MODEL_ITEM_ADD_LIST("模型ITEM列表批量新增", "/cms/modelItem/saveList"),
    CMS_MODEL_ITEM_UPDATE_LIST("模型ITEM列表批量更新", "/cms/modelItem/updateList"),
    CMS_MODEL_ITEM_DEL_LIST("模型ITEM列表批量删除", "/cms/modelItem/deleteList"),

    CMS_FILEUPLOAD("CMS文件上传接口","/cms/sftp"),

    FRIENDLINK("友情链接接口", "/cms/link"),
    FRIENDLINK_ONE("友情链接接口", "/cms/link/{friendlinkId}"),

    COMMENT("评论管理接口", "/cms/comment"),
    COMMENT_ONE("评论管理接口", "/cms/comment/{commentId}"),
    COMMENT_DELETELIST("评论批量删除","/cms/comment/deleteList"),
    COMMENT_SPLIST("评论批量审核","/cms/comment/spList"),

    COMMENT_TJ("评论统计", "/cms/comment/tj"),
    FILEUP("文件上传", "/message/sftp"),
    FILEUPBASE64("文件上传", "/message/sftp/upload"),

    CMS_QUESTION("新增调查问卷","/cms/question"),
    CMS_QUESTION_COPY("复制调查问卷","/cms/question/copy"),
    CMS_QUESTION_ID("调查问卷id","/cms/question/{id}"),
    CMS_QUESTION_STATUS("调查问卷状态修改","/cms/question/status/{id}"),
    CMS_QUESTION_SKIN("调查问卷背景皮肤修改","/cms/question/skinUrl/{id}"),
    CMS_SUBJECT_QUESTIONID("调查问卷题目","/cms/subjects/{questionId}"),
    CMS_SUBJECT_ID("题目id","/cms/subjects/select/{id}"),
    CMS_SUBJECT_ID_QUESTIONID("","/cms/subjects/{id}/{questionId}"),
    CMS_SUBJECT_COPY("题目新增","/cms/subjects/copy/{subjectId}"),
    CMS_SUBJECT_DEL_PAGE("页面删除","/cms/subjects/pages/{pages}/{questionId}"),
    CMS_QUESTION_RECOVERY_ID("查询单个问卷的回收率","/cms/question/recovery/{questionId}"),
    CMS_QUESTION_AVG_ANSWER_TIME("查询单个问卷的平均时间","/cms/answer/avg/{questionId}"),
    CMS_QUESTION_QUESTION_STATISTICS_LIST("问卷答题统计列表","/cms/question/selectdttj"),
    CMS_QUESTION_ACCESS_STATISTICS_LIST("问卷访问量统计列表","/cms/accessLog/selecttj"),
    CMS_QUESTION_ANSWER_STATISTICS_LIST("问卷回收量统计列表","/cms/answer/selecttj"),
    CMS_QUESTION_ANSWER("答题记录单个查询","/cms/answer/{id}"),
    CMS_QUESTION_ANSWER_LIST("答题记录列表查询","/cms/answer/list/{questionId}"),
    CMS_QUESTION_SUBJECT_ANSWER("单个题目答题记录查询","/cms/answer/answerList/{subjectsId}"),
    CMS_QUESTION_ANSWER_SUBMIT("答题记录提交","/cms/answer/batch"),
    CMS_QUESTION_ANSWER_DEL("答题记录批量删除","/cms/answer/{questionId}"),
    CMS_QUESTION_THEMES("问卷主题","/cms/images"),
//    SYSFILEUP("文件上传", "/message/sftp"),
    /*** 活动接口****/
    CMS_ACTIVITY("活动列表","/cms/event"),
    CMS_EVENTAPPLY("报名列表","/cms/eventApply"),
    CMS_EVENTAPPLY_DEL("报名列表","/cms/eventApply/{applyId}"),
    CMS_EVENTAPPLY_EVENTID("根据活动ID获取报名列表","/cms/eventApply/{applyId}"),
    CMS_EVENTAPPLY_LIST_DEL("报名批量删除","/cms/eventApply/deleteList"),
    CMS_EVENTAPPLY_LIST_SH("报名批量审核","/cms/eventApply/updateStatusList"),
    CMS_EVENTAPPLY_NO_LIST_SH("报名拒绝批量审核","/cms/eventApply/updateStatusNoList"),
    CMS_EVENTSPONSOR_SAVE("新增主办方","/cms/eventSponsor"),
    CMS_EVENT_SAVE("新增活动","/cms/event"),
    CMS_EVENTSPONSOR_UPD("修改主办方","/cms/eventSponsor/{sponsorId}"),
    CMS_EVENT_UPD("修改活动","/cms/event/{eventId}"),
    CMS_EVENTSPONSOR("主办方列表","/cms/eventSponsor"),
    CMS_EVENTSPONSOR_DEL("主办方删除","/cms/eventSponsor/{sponsorId}"),
    CMS_EVENT_ID("根据ID获取活动","/cms/event/{eventId}"),
    CMS_EVENT_APPLY_SELECTLLTJ("活动浏览统计","/cms/eventApply/selectlltj"),
    CMS_EVENT_APPLY_SELECTLLTJ_BM("报名统计","/cms/eventApply/selectbmtj"),
    /***************/


    /* 生成静态页 */
    STATIC_KNOWLEDGE_TAG("根据标签查询知识库","/bangbang/knowledgeBase/uc/listbytag"),

    CMS_KNOW_CJLY("采集来源列表","/bangbang/knowledgeBase/sourceList"),


    /* uc接口 */
    USER_LOGIN("用户登录接口", "/uc/admin/login"),
    GET_RSA_PK("获取RSA公钥", "/uc/admin/pk"),
    GET_SOA_ACCESS_TOKEN("接口访问权限请求", "/uc/app/login"),
    SYS_MENU("菜单接口", "/uc/admin/menu"),
    SYS_MENU_ONE("菜单接口", "/uc/admin/menu/one/{id}"),
    SYS_MENU_ID("菜单接口", "/uc/admin/menu/{id}"),
    SYS_MENU_ENABLE("菜单启用禁用", "/uc/admin/menu/enable"),
    OPERATOR("运营员管理接口", "/uc/admin/user"),
    OPERATOR_ID("运营员管理接口", "/uc/admin/user/{id}"),
    OPERATOR_ENABLE("运营员启用禁用", "/uc/admin/user/enable"),
    OPERATOR_PASSWORD("用户密码修改", "/uc/admin/user/password"),
    OPERATOR_PASSWORD_RESET("用户密码重置", "/uc/admin/user/password/{id}"),
    ROLE("角色接口", "/uc/admin/role"),
    ROLE_ID("角色单个接口", "/uc/admin/role/{id}"),
    ROLE_USER_ID("角色-用户关联查询", "/uc/admin/role/user/{id}"),
    ROLE_USER("角色-用户关联修改", "/uc/admin/role/user"),
    ROLE_ENABLE("角色-禁用启用", "/uc/admin/role/enable"),
    ORG("组织接口", "/uc/admin/org"),
    ORG_ID("组织单个接口", "/uc/admin/org/{id}"),
    ORG_ENABLE("组织单个接口", "/uc/admin/org/enable"),
    PROVINCE("省地区接口", "/uc/province"),
    CITY("市地区接口", "/uc/city/{parentId}"),
    AREA("区地区接口", "/uc/area/{parentId}"),
    BUSINESS_MSG("业务消息", "/uc/message"),
    SYS_CODE("数据字典接口", "/uc/dict"),
    SYS_CODE_TREE("数据字典接口", "/uc/dict/tree"),
    SYS_CODE_ONE("数据字典接口", "/uc/dict/{id}"),
    SYS_CODE_LEVEL("数据字典接口", "/uc/dict/firstlevel"),
    SYS_CODE_NAME_ID("数据字典接口", "/uc/dict/kv/{dictId}"),
    SYS_CODE_NAME("数据字典查询名称", "/uc/dict/name"),
    CUSTOMER_MANAGER_LIST("客户经理列表查询","/uc/adminService"),
    CUSTOMER_MANAGER_ADD("客户经理新增","/uc/adminService"),
    CUSTOMER_MANAGER_MODIFY("客户经理修改","/uc/adminService/{id}"),
    CUSTOMER_MANAGER_DELETE("客户经理删除","/uc/adminService/{id}"),
    CUSTOMER_MANAGER_VIEW("客户经理单个查询","/uc/adminService/{id}"),
    /***         定时任务接口     */
    SYS_TIME("定时任务列表","/uc/admin/cron"),
    SYS_TIME_ONE("根据jobName和jobGroup获取定时任务","/uc/admin/cron/{jobName}/{jobGroup}"),
    SYS_TIME_SAVE("新增定时任务","/uc/admin/cron"),
    SYS_TIME_UPD("修改定时任务","/uc/admin/cron/{taskId}"),
    SYS_TIME_DELETELIST("批量删除定时任务","/uc/admin/cron/deleteList"),
    SYS_TIME_DELETE("删除定时任务","/uc/admin/cron/{jobName}/{jobGroup}"),
    SYS_TIME_PAUSE("暂停定时任务","/uc/admin/cron/pause/{jobName}/{jobGroup}"),
    SYS_TIME_RESUME("激活定时任务","/uc/admin/cron/resume/{jobName}/{jobGroup}"),
    SYS_TIME_LIST("定时任务列表(无需登录)","/uc/admin/cron/list"),
    /************************/

    BUSINESS_MSG_SEND("消息接口","/uc/sendmsg/byqd"),
    BUSINESS_MSG_SENDV2("新消息接口","/uc/sendmsg/v2"),
    BUSINESS_MSG_SEND_BYQDBATCH("消息接口","/uc/sendmsg/byqdbatch"),
    INVOICE_PRINT("发票打印","/uc/invoice/export/print"),
    INVOICE_PRINTIMPORT("发票打印导入","/uc/invoice/import/print"),
    INVOICE_SEND("发票寄送","/uc/invoice/export/express"),
    INVOICE_SENDIMPORT("发票寄送导入","/uc/invoice/import/express/{expressCompId}"),
    ALIPAY_Q("支付宝交易结果查询","/uc/alipay/alipayquery"),
    POINTS_Q("积分交易结果查询","/uc/alipay/orderpayquery"),
    WEIXIN_PAYQ("微信支付交易结果查询","/uc/wxpay/wxorderquery"),
    WEIXIN_REFUNDQ("微信退款交易结果查询","/uc/wxpay/dowxrefundquery"),
    ALIPAY_REFUNDQ("支付宝交易结果查询","/uc/alipay/refund/{out_trade_no}/{out_request_no}"),
    TRADELOG_LIST("所有","/uc/tradelog"),
    TRADELOG_BILL("批量对账单","/uc/tradelog/bill"),
    TRADELOG_VALID("手工对账成功","/uc/tradelog/valid/{id}"),
    TRADELOG_INVALID("手工对账失败","/uc/tradelog/invalid/{id}"),
    PRIVLEGE_ALL("所有","/uc/uvip/privilegelevel"),
    PRIVLEGE_BYID("指定权益id查询","/uc/uvip/privilegelevel/privilege"),
    PRIVLEGE_BYLEVEL("按照会员查询","/uc/uvip/privilegelevel/level"),
    PRIVLEGE_PADD("按照特权更新","/uc/uvip/privilegelevel/updateprivilege/{privilege}"),
    PRIVLEGE_LADD("按照会员更新","/uc/uvip/privilegelevel/updatelevel/{level}"),
    EXCHANGE_EXPORT("退货快递导出","/uc/exchange/export"),
    EXCHANGE_IMPORT("退货快递导入","/uc/exchange/import"),
    EXCHANGE_LIST("退货列表","/uc/exchange"),
    EXCHANGE_LISTF("退货列表财务","/uc/exchange/finance"),
    EXCHANGE_INFO("退货信息","/uc/exchange/{id}"),
    EXCHANGE_AGREE("同意退货","/uc/exchange/agree/{id}"),
    EXCHANGE_DISAGREE("拒绝退货","/uc/exchange/disagree/{id}"),
    EXCHANGE_CONFIIRM("确认收货","/uc/exchange/confirm/{id}"),
    EXCHANGE_BACK("确认收货","/uc/exchange/back/{id}"),
    EXCHANGE_REFUND("确认收货","/uc/exchange/refund/{id}"),
    INVOICEBACK_LIST("发票退票列表","/uc/invoice/back"),
    INVOICEBACK_INFO("发票退票详情","/uc/invoice/back/{id}"),
    INVOICEBACK_CHECK("发票退票审核","/uc/back/check/{expressId}/{id}"),
    TAG_ENABLE("标签启用禁用","/uc/tag/{id}/{status}"),
    VIPPRIVILEGE_ENABLE("会员特权启用禁用","/uc/uvip/privilege/switch/{id}"),
    VIPLEVEL_ENABLE("会员等级启用禁用","/uc/uvip/level/{id}/{status}"),
    EXPRULE_ENABLE("经验值启用禁用","/uc/uexp/rule/{id}/{status}"),
    POINTRULE_ENABLE("积分启用禁用","/uc/upoints/rule/{id}/{status}"),
    UEXPLEVEL_ENABLE("经验值等级启用禁用","/uc/uexp/level/{id}/{status}"),
    API_UNSET("未授权API","/uc/api/apisetting/{appId}"),
    INVOICE_LIST("发票列表","/uc/invoice"),
    INVOICE_INFO("发票列表详情","/uc/invoice/{invoiceId}"),
    INVOICE_BILL("发票审批","/uc/invoice/billing"),
    INVOICE_INVALID("发票申请作废","/uc/invoice/invalid"),
    INVOICE_GET("获取发票","/uc/invoice/detail/select"),
    INVOICE_GETBYNO("获取发票NO","/uc/invoice/detail/invoice"),
    APPSET_BATCH("API批量授权","/uc/appsetting/list/{appId}"),
    APPSET_LIST("API授权列表","/uc/appsetting"),
    APPSET_INFO("API授权列表详细","/uc/appsetting/{appId}/{id}"),
    APPSET_ADD("API授权","/uc/appsetting/{appId}/"),
    APPSET_EDIT("API授权更新","/uc/appsetting/{appId}/{id}"),
    APPSET_DEL("API授权删除","/uc/appsetting/{appId}/{id}"),
    API_LIST("API列表","/uc/api"),
    API_INFO("API信息","/uc/api/{id}"),
    API_ADD("API添加","/uc/api"),
    API_EDIT("API编辑","/uc/api/{id}"),
    API_DEL("API删除","/uc/api/{id}"),
    INVOICEDT_DEL("发票仓库明细删除","/uc/invoice/detail/del/{id}"),
    INVOICEDT_DISABLE("发票仓库明细作废","/uc/invoice/detail/invalid/{id}"),
    INVOICEREPO_LIST("发票仓库","/uc/invoice/repo"),
    INVOICEREPO_ADD("发票仓库入库","/uc/invoice/repo"),
    INVOICEREPO_EDIT("发票仓库入库修改","/uc/invoice/repo/{id}"),
    INVOICEREPO_SELECT("单个发票仓库发票详情","/uc/invoice/repo/{id}"),
    INVOICEREPO_DEL("发票仓库删除","/uc/invoice/repo/{id}"),
    INVOICEREPO_DETIALLIST("发票仓库明细","/uc/invoice/detail"),
    INVOICEREPO_CODE("根据发票种类代码，获取发票仓库ID","/uc/invoice/repo/code/{code}"),
    INVOICEREPO_VALIDATE("发票仓库-验证唯一性，根据发票代码和发票号码","/uc/invoice/repo/validate"),
    INVOICELY_LIST("发票领用列表","/uc/invoice/use"),
    INVOICELY_ADD("发票领用新增","/uc/invoice/use"),
    INVOICELY_EDIT("发票领用修改","/uc/invoice/use"),
    INVOICELY_INFO("发票领用详情","/uc/invoice/use/{id}"),
    INVOICELY_DEL("发票领用删除","/uc/invoice/use/{id}"),
    INVOICELY_CHECK("发票领用审核","/uc/invoice/use/check/{id}"),
    INVOICELY_DIST("发票领用分发","/uc/invoice/dist/send"),
    INVOICELY_SIGN("发票领用签收","/uc/invoice/dist/sign/{id}"),
    INVOICELY_NUM("根据发票种类代码，获取发票仓库库存数，可用份数","/uc/invoice/use/num/{code}"),
    TAG_LIST("用户标签","/uc/tag"),
    TAG_ADD("用户标签","/uc/tag"),
    TAG_INFO("用户标签信息","/uc/tag/{id}"),
    TAG_EDIT("用户标签修改","/uc/tag/{id}"),
    TAG_DEL("用户标签删除","/uc/tag/{id}"),
    SYSTASK_INFO("系统任务信息","/uc/task/{id}"),
    CONSUMER_VIPLOG("用户VIP日志","/uc/uvip/log"),
    CONSUMER_VIPLOG_ORDER("用户VIP日志","/uc/uvip/log/order"),
    SYSTASK_LIST("系统任务列表","/uc/task"),
    VIPPRIVILEGE_DEL("会员特权删除","/uc/uvip/privilege/{id}"),
    VIPPRIVILEGE_ADD("会员特权新增","/uc/uvip/privilege"),
    VIPPRIVILEGE_EDIT("会员特权修改","/uc/uvip/privilege/{id}"),
    VIPPRIVILEGE_INFO("会员特权","/uc/uvip/privilege/{id}"),
    VIPPRIVILEGE_LIST("会员特权列表","/uc/uvip/privilege"),
    VIPLEVEL_ADD("会员等级新增","/uc/uvip/level"),
    VIPLEVEL_EDIT("会员等级修改","/uc/uvip/level/{id}"),
    VIPLEVEL_INFO("会员等级","/uc/uvip/level/{id}"),
    VIPLEVEL_LIST("会员等级列表","/uc/uvip/level"),
    EXPRULE_ADD("经验值规则新增","/uc/uexp/rule"),
    EXPRULE_EDIT("经验值规则修改","/uc/uexp/rule/{id}"),
    EXPRULE_INFO("经验值规则","/uc/uexp/rule/{id}"),
    EXPRULE_LIST("经验值规则列表","/uc/uexp/rule"),
    POINTRULE_ADD("积分规则新增","/uc/upoints/rule"),
    POINTRULE_EDIT("积分规则修改","/uc/upoints/rule/{id}"),
    POINTRULE_INFO("积分规则","/uc/upoints/rule/{id}"),
    POINTRULE_LIST("积分规则列表","/uc/upoints/rule"),
    CONSUMER_POINTLOG("积分列表","/uc/upoints/log"),
    CONSUMER_AMOUNT("礼包金额列表","/uc/gift/uamount/list"),
    CONSUMER_EXPLOG("经验列表","/uc/uexp/log"),
    CONSUMER_SJLOG("修改手机号码日志列表","/uc/admin/operation"),
    CONSUMER_LIST("用户列表","/uc/user"),
    CONSUMER_INFO("用户详细信息","/uc/user/admin/{id}"),
    CONSUMER_STATUS("用户详细启用禁用","/uc/user/{id}/{status}"),
    CONSUMER_INFO_BY_NAME_PHONE("用户详细信息","/uc/user/u/{usernameOrPhone}"),
    CONSUMER_MODIFY("用户信息修改","/uc/user/{id}"),
    USER_ADDRESS_INFO("收货地址单个","/uc/address/{userId}/{id}"),
    USER_ADDRESS_LIST("收货地址列表","/uc/address/{userId}"),

    LOTTERYACTIVITYIP_LIST("抽奖活动ip屏蔽","/uc/lotteryactivityip"),
    LOTTERYACTIVITYIP_INFO("抽奖活动ip屏蔽单个","/uc/lotteryactivityip/{id}"),
    TAXPAYERBIND_LIST("纳税人绑定查询","/uc/nsrbindquery"),
    TAXPAYERBIND_DZSB("纳税人绑定查询","/uc/nsrbindquery/dzsb/{id}"),
    TAXPAYERBIND_HNDS("纳税人绑定查询","/uc/nsrbindquery/hnds/{id}"),
    TAXPAYERBIND_HNGS("纳税人绑定查询","/uc/nsrbindquery/hngs/{id}"),
    TAXPAYERBIND_PWDLOG("纳税人绑定查询修改密码日志列表","/uc/shb/restpwdloglist"),
    CONSUMER_TAGS("人员标签查询","/uc/tag/taglist/{userId}"),
    CONSUMER_TAGADD("人员标签添加","/uc/tag/user/{id}/{tagId}"),
    CONSUMER_TAGBATCH("人员标签批量添加","/uc/tag/user/{id}"),
    CONSUMER_TAGSDEL("人员标签取消","/uc/tag/user/{id}/{tagId}"), 
    CONSUMERS_TAGBATCH("用户批量打标签","/uc/tag/batch/{subject}"),
    SYSTASK_ADD("系统任务添加","/uc/task"), 
    SYSTASK_EDIT("系统任务编辑","/uc/task/{id}"),
    SYSTASK_DEL("系统任务删除","/uc/task/{id}"), 
    LOGISTIC_LIST("物流公司列表","/uc/express/comp"),
    LOGISTIC_INFO("物流公司查看","/uc/express/comp/{id}"),
    LOGISTIC_ADD("物流公司新增","/uc/express/comp"),
    LOGISTIC_EDIT("物流公司修改","/uc/express/comp/{id}"),
    LOGISTIC_DEL("物流公司删除","/uc/express/comp/{id}"), 
    SHIPPING_DEL("配送方式删除","/uc/delivery/{id}"), 
    SHIPPING_EDIT("配送方式编辑","/uc/delivery/{id}"), 
    SHIPPING_ADD("配送方式添加","/uc/delivery"), 
    SHIPPING_INFO("配送方式信息","/uc/delivery/{id}"), 
    SHIPPING_LIST("配送方式列表","/uc/delivery"),
    SHIPPING_ENABLE("配送方式禁用","/uc/delivery/enable"),
    GOODSCATEGORY_LIST("商品分类列表","/uc/goods/category"),
    GOODSCATEGORY_INFO("商品分类查看","/uc/goods/category/{id}"),
    GOODSCATEGORY_ADD("商品分类新增","/uc/goods/category"),
    GOODSCATEGORY_EDIT("商品分类修改","/uc/goods/category/{id}"),
    GOODSCATEGORY_DEL("商品分类删除","/uc/goods/category/{id}"),
    UEXPLEVEL_LIST("经验值等级列表","/uc/uexp/level"),
    UEXPLEVEL_INFO("经验值等级查看","/uc/uexp/level/{id}"),
    UEXPLEVEL_ADD("经验值等级新增","/uc/uexp/level"),
    UEXPLEVEL_EDIT("经验值等级修改","/uc/uexp/level/{id}"),
    UEXPLEVEL_DEL("经验值等级删除","/uc/uexp/level/{id}"),
    GOODS_DETAILLIST("产品管理列表","/uc/goods"),
    GOODS_LIST("产品列表","/uc/goods/user"),
    GOODS_INFO("产品查看","/uc/goods/{id}"),
    GOODS_ADD("产品新增","/uc/goods"),
    GOODS_EDIT("产品修改","/uc/goods/{id}"),
    GOODS_CHECK("产品审核","/uc/goods/check"),
    CURRICULUM_GOODS_INFO("课程产品查看","/uc/goods/curriculum/{id}"),
    ORDER_LIST("订单管理","/uc/order"),
    MYORDER_LIST("我的销售订单","/uc/order/myOrder"),
    MYORDERMONEY_LIST("我的销售订单金额统计","/uc/order/myOrder/money"),
    ORDER_BACK_LIST("退单管理","/uc/order/back"),
    ORDER_INFO("单个订单信息管理","/uc/order/admin/select/{orderNo}"),
    ORDER_EXPORT("订单信息导出","/uc/order/export"),
    ORDER_IMPORT("订单信息导入","/uc/order/import/{expressCompId}"),
    ORDER_SEND("订单发货","/uc/order/send"),
    ORDER_DEL("订单删除","/uc/order/admin/delete/{userId}/{id}"),
    ORDER_RETURN("订单退单","/uc/order/return/{id}/{goodsId}"),
    PRODUCTREPO_LIST("商品库存列表","/uc/product/productrepo"),
    PRODUCTREPO_ADD("商品库存入库","/uc/productrepo/income"),
    PRODUCTREPO_MINUS("商品库存出库","/uc/productrepo/outcome"),
    PRODUCTREPO_INFO("商品库存查询","/uc/product/productrepo/select"),
    PRODUCTREPO_EDIT("商品库存修改","/uc/product/productrepo/{id}"),
    PRODUCTREPO_DEL("商品库存删除","/uc/product/productrepo/{id}"),
    GOODS_PRODUCT("产品参数查询","/uc/product/select/{goodsId}"),
    GOODS_PROPRICE("会员价格列表","/uc/uvipprice/select/{productId}"), 
    REALNAMEVALIDA_LIST("实名认证列表","/uc/realnamevalidation"),
    REALNAMEVALIDA_VALIDA("实名认证信息","/uc/realnamevalidation/{userId}/{validStatus}"),
    USER_EDITPHONE("修改手机号码","/uc/user/phone/{id}"),
    USER_RESETPWD("重置密码","/uc/user/resetpwd"),
    REALNAMEVALIDA_REVALIDA("实名认证","/uc/realnamevalidation/revalidation/{userId}"),
    GZH_LIST("微信公众号","/uc/wxgzh/list"),
    GZHMENU_LIST("微信公众号菜单","/uc/wxmenu/db/list"),
    MSGAUTO_GZHMENU_update("微信公众号菜单修改","/uc/wxmenu/db/{id}"),
    MSGAUTO_GZHMENU_creat("微信公众号菜单添加","/uc/wxmenu/db/creat"),
    MSGAUTO_GZHWXMENU_creat("微信公众号菜单","/uc/wxmenu/create"),
    MSGAUTO_GZH_update("微信公众号修改","/uc/wxgzh/{id}"),
    APP_LIST("APP列表","/uc/app"),
    APP_ADD("APP列表","/uc/app/register"),
    APP_INFO("APP信息","/uc/app/{id}"),
    APP_EDIT("APP编辑","/uc/app/{id}"),
    APP_ENABLE("APP禁用","/uc/app/{id}"),
    APPINTERFACE_LIST("APP接口列表","/uc/app/setting/{appId}"),
    APPINTERFACE_INFO("APP接口信息","/uc/app/setting/{appId}/{id}") ,
    NOTICE_INFO("通知公告查看","/cms/notice/{id}"),
    NOTICE_ADD("通知公告新增","/cms/notice"),
    NOTICE_EDIT("通知公告修改","/cms/notice/{id}"),
    NOTICE_LIST("通知公告列表","/cms/notice"),
    NOTICE_DEL("通知公告删除","/cms/notice/{id}"),
    ADPAGE_INFO("广告图片查看","/cms/adpage/{id}"),
    ADPAGE_ADD("广告图片新增","/cms/adpage"),
    ADPAGE_EDIT("广告图片修改","/cms/adpage/{id}"),
    ADPAGE_DEL("广告图片删除","/cms/adpage/{id}"),
    ADPAGE_LIST("广告图片列表","/cms/adpage"),
    ADPAGELOG_LIST("广告记录列表","/cms/adpagelog"),
    ADPAGES_LIST("前端广告图片列表","/cms/adpages"),
    WXUSER_INFO("单个微信用户查看","/cms/wxuser/{id}"),
    WXUSER_SYNCHRO("同步微信用户到本地数据库","/cms/wxuser/synchro"),
    WXUSER_SYNCHRO_ONE("从微信服务器同步单个用户信息","/cms/wxuser/synchro/{id}"),
    WXUSER_LIST("微信用户列表","/cms/wxuser/list"),
    MSGAUTO_GJC_LIST("关键词自动回复列表","/uc/wxremsg/db/keyList"),
    MSGAUTO_MSG_QRY("消息自动回复查询","/uc/wxremsg/db/get"),
    MSGAUTO_MSG_creat("自动回复消息创建","/uc/wxremsg/db/creat"),
    MSGAUTO_MSG_update("自动回复消息修改","/uc/wxremsg/db/{id}"),
    MSGAUTO_MSG_QRYID("消息自动回复查询l","/uc/wxremsg/db/get/{id}"),
    MSGAUTO_MSG_DEL("消息自动回复删除","/uc/wxremsg/db/{id}"),
    QRCODE_LIST("微信二维码","/uc/qrcode"),
    QRCODE_INFO("微信二维码查询单个","/uc/qrcode/{id}"),
    LOTTERY_LIST("积分抽奖列表","/uc/lottery"),
    LOTTERY_INFO("积分抽奖单个","/uc/lottery/{id}"),
    LOTTERYLOG_LIST("积分抽奖日志列表","/uc/lotterylog"),
    LOTTERYLOG_INFO("积分抽奖日志单个","/uc/lotterylog/{id}"),
    LOTTERYTEMPLATE_LIST("抽奖模版","/uc/lotterytemplate"),
    LOTTERYTEMPLATE_INFO("抽奖模版单个","/uc/lotterytemplate/{id}"),
    LOTTERYTime_LIST("积分抽奖时间","/uc/lotterytime"),
    LOTTERYTime_INFO("积分抽奖时间单个","/uc/lotterytime/{id}"),
    LOTTERYACTIVITY_LIST("积分抽奖活动","/uc/lotteryactivity"),
    LOTTERYACTIVITY_INFO("积分抽奖活动单个","/uc/lotteryactivity/{id}"),
    LOTTERYACTIVITYPRIZE_LIST("积分抽奖活动商品","/uc/lotteryactivityprize"),
    LOTTERYACTIVITYPRIZE_INFO("积分抽奖活动商品单个","/uc/lotteryactivityprize/{id}"),
    EXP_CODEXQ("经验值规则查询","/uc/experience/codex/{uexpruleId}"),
    EXP_CODEXA("经验值规则添加","/uc/experience/codex/{uexpruleId}"),
    REDPACK_SECRET("红包查看信息","/uc/wx/redpack/hbinfo/{id}"),
    REDPACK_RESEND("重新发送红包","/uc/wx/redpack/resend/{id}"),
    REDPACK_LIST("红包查看列表","/uc/wx/redpack"),
    REDPACK_IMPORT("红包查看列表","/uc/wx/redpack/import"),
    REDPACK_DEL("红包口令删除","/uc/wx/redpack/{id}"),
    REDPACK_BATCH("红包口令批量删除","/uc/wx/redpack/batchdelete"),
    WXACTIVITY_INFO("微信红包活动查看","/uc/wx/activity/{id}"),
    WXACTIVITY_LIST("微信红包活动列表","/uc/wx/activity"),
    ADMINLOG_LIST("操作员日志列表","/uc/adminlog"),
    APP_TOTAL("APP接口访问总次数","/uc/log/api"),
    APP_API_TOTAL("APP接口访问次数","/uc/log/api/app"),
    APP_API_LIST("APP接口访问次数详情","/uc/log/api/list"),
    SZHDXX_LIST("查询税种核定","/message/hngs/post?api=/sssearch/nsrjcxx4cszj"),
    NSRZGLX_LIST("查询一般纳税人资格","/message/hngs/post?api=/sscx/cszj/ybnsrzg"),
    YQWRDNSR_LIST("逾期未认定","/message/hngs/post?api=/sscx/cszj/yqwrd"),
    JZJTZG_LIST("查询即征即退资格","/message/hngs/post?api=/sscx/cszj/jzjtzg"),
    ZZSNCPBA_LIST("查询增值税农产品备案","/message/hngs/post?api=/sscx/cszj/zzsncpba"),
    ZZSZFJG_LIST("查询增值税总分机构","/message/hngs/post?api=/sscx/cszj/zzszfjg"),
    JYZSBA_LIST("查询简易征收备案","/message/hngs/post?api=/sscx/cszj/jyzsba"),
    CKTSBA_LIST("查询出口退税备案","/message/hngs/post?api=/sscx/cszj/cktsba"),
    WHSYJSFDJ_LIST("查询文化事业建设费登记","/message/hngs/post?api=/sscx/cszj/whsyjsf"),
    CWBBBA_LIST("查询财务报表备案","/message/hngs/post?api=/sscx/cszj/cwbbba"),
    SDSDJHZ_LIST("查询文化事业建设费登记","/message/hngs/post?api=/sscx/cszj/sdsdjhz"),
    SMRZXX_LIST("查询实名认证信息","/message/hngs/get"),
    DBSX_TOTAL("待办事项总数","/uc/todolist"),
    ORDERCOUNT_TOTAL("统计订单总数","/uc/stat/order"),
    MOBILEMSG_LOG("短信消息日志","/message/mobile/msg/log"),
    MOBILEMSG_QUERY("根据发送渠道新增短信查询日志","/message/channel/msgquery"),
    MOBILEMSG_LOG_TB("短信消息日志同步","/message/ali/detail"),
    CWBBYJBHD_LIST("查询财务报表备案","/message/hngs/post?api=/sscx/cszj/cwbbyjbhd"),
    REDPACK_EDIT("微信红包口令修改","/uc/wx/redpack/{id}"),
    PUBLICKEY_GET("电子税局公钥获取","/message/hngs/getpublickey"),
    WXMODLEMSG_LIST("微信模版消息列表","/uc/wxTemplate/list"),
    WXMODLEMSG_SYNC("同步微信模版消息","/uc/wxTemplate/synchro"),
    MOBILEMODLEMSG_LIST("短信模版消息列表","/message/upyun/templates"),
    MOBILEMODLEMSG_SYNC("同步短信模版消息","/message/upyun/synchronize/template"),
    USERMSG_YW_LIST("用户业务消息列表","/message/business/username"),
    USERMSG_SX_LIST("用户私信消息列表","/message/user/msg"),
    INVOICEKJLOG_LIST("短信模版消息列表","/uc/einvocie/querylist"),
    INVOICEKJLOG_SYNC("同步电子发票开具信息","/uc/invoice/dzfp/check"),
    WXMODLEMSGLOG_LIST("微信模版消息日志列表","/uc/wxtemplatesendlog"),
    REGISTERUSER_COUNT("注册用户数统计","/uc/user/statis/month"),
    REGISTERUSER_LOOK("注册用户信息","/uc/user/statis/list"),
    USERLOST_RATE("用户流失率统计","/uc/user/statis/loss"),
    USERRETEN_RATE("用户留存率统计","/uc/user/statis/reta"),
    CONSUME_RATE("用户消费能力分析,用户列表","/uc/user/statis/consume"),
    CONSUME_RFM("用户消费能力分析","/uc/user/statis/consume/rfm"),
    USEREXPLEVEL_RATE("用户经验值等级统计","/uc/user/statis/explevel"),
    USERVIPLEVEL_RATE("用户会员等级统计","/uc/user/statis/viplevel"),
    USERVIPLEVEL_ALLINFO("用户会员等级统计,全部用户明细","/uc/user/statis/viplevel/all/uinfo"),
    USERVIPLEVEL_INCREASE("用户会员等级统计,新增用户明细","/uc/user/statis/viplevel/increase/uinfo"),
    USERACTIVE_RATE("用户活跃度统计","/uc/user/statis/liveness"),
    USERACTIVEDETAIL_RATE("用户活跃度统计明细","/uc/user/statis/liveness/detail"),
    USERACTIVE_INFO("用户活跃度统计用户明细","/uc/user/statis/liveness/detail/uinfo"),
    USERTAG_RATE("用户标签分析统计","/uc/user/statis/tag"),
    USERTAG_INFO("用户标签分析统计,用户明细","/uc/user/statis/tag/uinfo"),
    USERSERVICECOMP_RATE("用户服务企业情况统计","/uc/user/statis/bind"),
    USERSERVICECOMP_INFO("用户服务企业情况统计","/uc/user/statis/bind/list"),
    USERAGE_RATE("用户年龄分布统计","/uc/user/statis/age"),
    USERAGE_INFO("用户年龄分布统计,用户明细","/uc/user/statis/age/list"),
    USERSEX_RATE("用户性别分布统计","/uc/user/statis/sex"),
    USERSEX_INFO("用户性别分布统计,用户明细","/uc/user/statis/sex/list"),
    USERAREA_RATE("用户区域分布统计","/uc/user/statis/region"),
    USERAREA_INFO("用户区域分布统计,用户明细","/uc/user/statis/region/uinfo"),
    COMPBING_RATE("企业绑定情况统计","/uc/user/statis/bind/count"),
    COMPBING_INFO("企业绑定情况统计,企业详情","/uc/user/statis/bind/count/info"),
    COMPLOGIN_RATE("企业登录情况统计","/uc/user/statis/bind/login"),
    COMPLOGIN_INFO("企业登录情况统计,企业详情","/uc/user/statis/bind/login/info"),
    USERBEHAVIOR_RATE("软件用户行为分析","/bangbang/record/statis"),
    USERBEHAVIOR_INFO("软件用户行为分析,用户明细","/bangbang/record/statis/list"),
    COMPUSING_RATE("企业使用情况统计","/bangbang/record/statis/company"),
    COMPUSING_INFO("企业使用情况统计,用户明细","/bangbang/record/statis/company/list"),
    REDISGL_LIST("微信模版消息日志列表","/message/redis"),
    REDISGL_ONE("微信模版消息日志列表","/message/redis/{key}"),
    REDISGL_FLUSHDB("微信模版消息日志列表","/message/redis/flushdb"),
    GIFT_LIST("会员礼物列表","/uc/gift"), 
    GIFT_INFO("会员礼物查看","/uc/gift/{id}"),
    GIFTAPPLY_INFO("会员礼物申请列表查看","/uc/gift/apply/list"), 
    GIFTAPPLY_CHECK("会员礼物申请审核","/uc/gift/apply/check"), 
    GIFTAPPLY_SEND("会员礼物申请发货","/uc/gift/apply/send"),
    GIFTAPPLY_LOG("会员礼物申请日志","/uc/gift/applylog/{applyId}"),
    GIFTAPPLY_LIST("会员礼物申请日志","/uc/gift/apply/{applyId}"),
    YYMSGSEND_LIST("运营消息推送","/uc/operate/message"),
    YYMSGSEND_ONE("单个运营消息推送","/uc/operate/message/{id}"),
    YYMSGSEND_REUSE("运营消息推送复用","/uc/operate/message/reuse/{id}"),
    REGION_LIST("区域列表查询","/uc/provincecityarea"),
    YYMSGSEND_SEND_LIST("运营消息推送情况","/uc/operate/message/log"), 
    BSRL_LIST("办税日历查询","/uc/user/bsrl"),
    BSRL_EDIT("办税日历查询","/uc/user/bsrl"),
    BSRL_ADD("办税日历查询","/uc/user/bsrl"),
    BSRL_DEL("办税日历查询","/uc/user/bsrl/{id}"),
    COUPON_LIST("优惠券列表查询","/uc/coupon"),
    COUPONACTIVITY_LIST("优惠券活动列表查询","/uc/coupon/activity"),
    COUPONACTIVITYS_LIST("前端用户可用优惠券活动列表查询","/uc/coupon/activities"),
    COUPON_ONE("单个优惠券查询","/uc/coupon/{id}"),
    COUPONACTIVITY_ONE("单个优惠券活动查询","/uc/coupon/activity/{id}"),
    COUPONUSER_LIST("优惠券使用情况列表查询","/uc/coupon/user"),
    COUPONUSER_ORDER("优惠券使用情况列表查询","/uc/coupon/user/order"),
    SUBSCRIPTION_LIST("消息订阅设置列表","/message/subscription"),
    SUBSCRIPTION_INFO("消息订阅设置查看","/message/subscription/{id}"),
    SUBSCRIPTION_ADD("消息订阅设置新增修改","/message/subscription"),
    SUBSCRIPTION_DEL("消息订阅设置删除","/message/subscription/{id}"),
    PRODUCTSPREAD_LIST("产品宣传列表查询列表","/cms/product/spread"),
    PRODUCTSPREAD_ONE("产品宣传列表查询列表","/cms/product/spread/{id}"),
    MYCONSTOMERS_LIST("我的客户列表","/uc/admin/spread/myconstomers"),
    MYSPREAD_QRCODE("我的产品推广码","/uc/admin/spread/myspreadurl"),
    REGISTERCOMP_COUNT("企业注册数统计","/uc/v2/dzsbregisterstat"),
    REGISTERCOMP_DETAIL("注册企业详情","/uc/v2/dzsbregisterstat/{date}"),
    LONG2SHORT_WX("微信长链接转短链接接口","/uc/long2short"),
    LONG2SHORT_TINY("tiny长链接转短链接接口","/uc/tinyurl"),
    CREATEORDER_ADD("个人产品代客下单","/uc/order/submit/{userId}"),
    ALIPAY_QRCODE("支付宝支付二维码","/uc/alipay/paycode"),
    COURSE_QUERYByVip_LIST("会员需要购买的课程查询","/bangbang/curriculum/selectListByVIP"),
    WEIXIN_QRCODE("微信支付二维码","/uc/wxpay/payorder");

    
    public String describe;

    public String uri;

    private ConstantsUri(String describe, String uri) {
        this.describe = describe;
        this.uri = uri;
    }

    public String toString() {
        return this.uri;
    }
}
